version: '3.9'
services:
  web:
    image: nginx:latest
    hostname: nginx
    env_file:
      - ".env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - sites:/var/www/html/
      - sites:/usr/share/nginx/html/
      - nginx-conf:/etc/nginx/
      - nginx-ssl:/etc/nginx/ssl/
    links:
      - mariadb
      - php
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - php
      - mariadb
    networks:
      - lemp82
  php:
    build: ../../php/82
    hostname: php
    env_file:
      - ".env"
    volumes:
      - sites:/var/www/html/
      - php-conf:/usr/local/etc/
    expose:
      - "9000"
    environment:
      - MYSQL_HOST=mysql
    networks:
      - lemp82
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    command: --max_allowed_packet=130023424
    ports:
      - "3306:3306"
    env_file:
      - ".env"
    volumes:
      - mariadb:/var/lib/mysql/
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - lemp82
networks:
  lemp82:
    driver: bridge
volumes:
  sites:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./../../../Sites/
  nginx-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./../../nginx/conf/
  nginx-ssl:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./../../nginx/ssl/
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./../../mariadb/
  php-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./../../../php/82/conf/